apiVersion: nais.io/v1
kind: Naisjob
metadata:
  annotations:
    nais.io/read-only-file-system: "false"
  labels:
    team: teamia
  name: ia-key-metrics
  namespace: teamia
spec:
  image: {{ image }}
  resources:
    limits:
      memory: 8Gi
    requests:
      memory: 1Gi
  ttlSecondsAfterFinished: 340
  schedule: "0 5-15/1 * * *"
  backoffLimit: 2
  accessPolicy:
    outbound:
      rules:
        - application: reops-proxy
          namespace: team-researchops
      external:
        - host: data.nav.no
  gcp:
    bigQueryDatasets:
      - name: ia_tjenester_metrikker
        permission: READ
  envFrom:
    - secret: teamia-nada-secret # value is the secret name in Google Secret Manager
  env:
    - name: NADA_HOST
      value: "data.nav.no"
    - name: QUARTO_ID
      value: "2f6249ef-67bc-4fe6-bd35-502f2e739c4e"
